### ISSUE TITLE
Context property units conflicts with the QQC2 theme units

### ISSUE THREAD

**Issue by bhush9** [maliit/keyboard#10]
So we have Plasma QQC2 theme which (unfortunately ab)uses the context properties, one such property registered is, units, https://api.kde.org/frameworks/plasma-framework/html/classUnits.html

Now, maliit itself also registers the context property called units, which have totally different API/ABI then one in the theme.

I am not saying that what Plasma theme is doing is "correct" but we are currently in situation where solving this in plasma-framework would essentially means the breaking API/ABI compat. I am not sure what could be correct solution though..

Currently what we plan to do is write a wrapper for maliit-keyboard which sets QT_QUICK_CONTROLS_STYLE=Default environment variable which makes it "work". But this does not seem like a solution

Any thoughts on how to solve this issue?

PS: context properties are going away in Qt 6 as far as I understand anyway...

**Comment by bhush9** [comment]
CC: @mariogrip @aleixpol

**Comment by jpetersen** [comment]
I think it was just some compatibility thing which was introduced to remove the UbuntuComponents dependency.

So yes we can maybe just remove it replace it with something else

**Comment by jpetersen** [comment]
Removed it for now as a temporary fix. We can introduce some better replacement
