### ISSUE TITLE
Maliit on PinePhone is Causing Plasma Mobile to Crash.

### ISSUE THREAD

**Issue by FedX-sudo** [maliit/keyboard#121]
I know I have had a very similar issue in the past, but astonishingly this appears to be totally different cause of the issue than my previous bug caused by auto-detection of a keyboard on a tablet. 

I am using a PinePhone Beta Edition running Manjaro Unstable Plasma Mobile, and since updating to the latest version of Maliit, I have found activating the on screen keyboard causes the Plasma Mobile UI to crash and restart. The keyboard never shows up, and after a few seconds, I get a black screen with `^@^@^@` and then Plasma restarts. I am not sure if this is an issue with Maliit or Plasma itself, and any help would be great. Thank you!

**Comment by dobey** [comment]
This appears to be a crash in kwin, due to some changes related to inputpanel-shell on that side, and is not caused by maliit itself.

**Comment by FedX-sudo** [comment]
I was afraid of that and sorry to wast your time, I am going to fall back from the unstable branch of KDE to stable. Thanks for such a great project and for pointing me in the right direction!
