### ISSUE TITLE
cmake error installing

### ISSUE THREAD

**Issue by bestlt** [maliit/keyboard#125]
when trying to compile from the latest release cmake returns these error:CMake Warning at CMakeLists.txt:35 (find_package):

  By not providing "FindQt5Feedback.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "Qt5Feedback", but CMake did not find one.

  Could not find a package configuration file provided by "Qt5Feedback" with
  any of the following names:

    Qt5FeedbackConfig.cmake
    qt5feedback-config.cmake

  Add the installation prefix of "Qt5Feedback" to CMAKE_PREFIX_PATH or set
  "Qt5Feedback_DIR" to a directory containing one of the above files.  If
  "Qt5Feedback" provides a separate development package or SDK, be sure it
  has been installed.
Is it some packages missing?

**Comment by dobey** [comment]
Yes, as the error says, you will need QtFeedback in order to build the keyboard. In debian systems it is `qt5feedback-dev` which you'll need to install. This is not a new requirement and has been here for a long time.
