### ISSUE TITLE
maliit-keyboard not opening on wayland

### ISSUE THREAD

**Issue by bestlt** [maliit/keyboard#126]
Hello,
after installing maliit-keyboard (and maliit-framework) on ubuntu (compile went without any errors) the keyboard refuses to show up.
Thank you for your help
[keyboard.log](https://github.com/maliit/keyboard/files/8528577/keyboard.log)

**Comment by dobey** [comment]
```
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
```
Is the latter set in the environment of `maliit-keyboard` process? Also, GNOME has it's on OSK and I'm not sure if maliit will work under it even when connecting via Wayland. It does however work fine on Plasma Mobile and Plasma Desktop (and probably others that aren't GNOME), with Wayland.

**Comment by bestlt** [comment]
But it couldn't be used in X11
[keyboard.log](https://github.com/maliit/keyboard/files/8539742/keyboard.log)

**Comment by dobey** [comment]
> But it couldn't be used in X11

Please be more specific about how you are running the keyboard, the environment (ie, `QT_QPA_PLATFORM` and such) it has, and what apps you are testing it with. Under X11 of course GTK apps won't just work, as you'll need also [inputcontext-gtk](https://github.com/maliit/inputcontext-gtk) installed and loaded via `GTK_IM_MODULE=maliit` environment variable. It only has support for gtk2 and gtk3 currently. For Qt apps under X11, you'll need `QT_IM_MODULE=maliit` environment variable.

The log output is also not showing anything useful. You might get more details by running the keyboard with `MALIIT_DEBUG=1` in the environment, but I suspect it will also be just as useless.
