### ISSUE TITLE
Is is possilbe to enable maliit keyboard in Phosh?

### ISSUE THREAD

**Issue by advzhangyang** [maliit/keyboard#152]
Hello, I would like to use Maliit keyboard since it supports Chinese inputs. The squeekboard is not supported Chinese inputs.
Is is possilbe to enable maliit keyboard in Phosh?Thanks.

**Comment by advzhangyang** [comment]
Hi，I am developing debian11 for mobile device(rk3588) and working on maliit keyboard and phosh（because maliit keyboard supports Chinese inputs. I am trying to compile maliit keyboard. Is is possilbe to enable maliit keyboard in Phosh?thanks

**Comment by advzhangyang** [comment]
Currently I am using x11.

**Comment by dobey** [comment]
This is more a question for Phosh developers, I think. Phosh implements the Wayland text input protocols a bit differently than other compositors.

Also, there is no Gtk4 input context plugin for maliit, so unless everything is gtk3 or gtk2, where text input is required, it won't work for X11 either.

**Comment by advzhangyang** [comment]
Thanks，I will ask phosh at the same time.
