### ISSUE TITLE
Nothing provides "libQt5Core.so.5(Qt_5.15.2_PRIVATE_API)(64-bit)"

### ISSUE THREAD

**Issue by MatsG23** [maliit/keyboard#156]
When I try to install maliit-framework (same error with maliit-keyboard), the package manager tells me that 
```Nothing provides "libQt5Core.so.5(Qt_5.15.2_PRIVATE_API)(64-bit)" required by maliit-framework-2.2.0-1.14.x86_64```.

I use openSUSE Tumbleweed 220804 and added your [software repository](http://download.opensuse.org/repositories/M17N:/Maliit/openSUSE_Factory/). What do I need to install to provide that private API? I have already tried installing Qt5.15.2 from the developers page and installing `libqt5-qtbase`.

**Comment by dobey** [comment]
I do not know who manages that repository, but it is not us. You will have to contact whomever owns it about issues with it. I do not know what build of Qt is was built against. Please check the package information and contact whomever maintains that package. Thanks.

**Comment by dobey** [comment]
> According to the GitHub user page of Maliit, this is the official package repository for maliit packages.

I would say that's a bug with the site then. We don't provide any "official" binary packages at this point. There seems to be some recent comment regarding your mentioned issue. You may wish to contact the maintainer of the package there.

**Comment by mpeter50** [comment]
This unofficial repository is still listed as official on your webpage, and it is very misleading.
Could you please remove the repository from there, or move it to the unofficial section?

But also, it seems the package is actually maintained by a project member: Jan Arne Petersen.
They are [a member of](https://github.com/orgs/maliit/people) the parent github organization.

The link to the [repository](https://download.opensuse.org/repositories/M17N:/Maliit/) was added by him to the webpage, [here](https://github.com/maliit/maliit.github.io/blame/a4fa0daccfd4af9d528a59ca59c1c26b861469dc/installing.md).

[This](https://build.opensuse.org/repositories/M17N:Maliit) is the repository's page on the SUSE Open Build Service.
According to the [users tab](https://build.opensuse.org/project/users/M17N:Maliit) on this page, the mentioned maintainer is a maintainer of that repository too.
