### ISSUE TITLE
Keyboard forever in light mode

### ISSUE THREAD

**Issue by reulew** [maliit/keyboard#159]
Nothing I do can change the keyboard to dark mode. Running maliit keyboard 2.3.1 on Plasma 5.25.4 using Wayland. This seems like a similar issue to issue #145 (without the transparency part) but the solution there did not work for me. The documentation does not mention theming. Some people seem to have changed the keyboard to a dark theme by running `gsettings set org.maliit.keyboard.maliit theme BreezeDark` but that also did not work.

**Comment by hedmo** [comment]
hi

just updated and having the same issue. i have been using the gsettings metod before but now it does not work any more.

regards hedmo

**Comment by dobey** [comment]
Unfortunately, Plasma desktop doesn't set the `QT_QUICK_CONTROLS_STYLE` environment variable for child applications, as apparently there are still some issues with different QtQuick applications, depending on which style is used. This results in the KDE platform theme not being loaded automatically in maliit-keyboard, and the default QtQuick Controls 2 style being used instead.

If one sets this variable to either `org.kde.breeze` or `org.kde.desktop` for the `maliit-keyboard` process, it should then use the correct theme colors under Plasma. This is more an issue in KDE, though I'm not quite sure what the correct fix would be yet.

**Comment by reulew** [comment]
@dobey How would one do what you described? The keyboard is not an app you launch so there's no place to add a variable like that. Also I don't think I want the change to be global. Thanks for your help. I really appreciate your work as a project maintainer.

**Comment by dobey** [comment]
You could perhaps create a wrapper script as `/usr/local/bin/maliit-keyboard` that just does:

```
#!/bin/sh

export QT_QUICK_CONTROLS_STYLE=org.kde.desktop
exec /usr/bin/maliit-keyboard
```

Assuming that `$PATH` is correctly ordered for kwin, then this should get preference over the main binary. Don't forget to `chmod a+x` said script. :)
