### ISSUE TITLE
Some usability issues when used on a phone

### ISSUE THREAD

**Issue by bjorn3** [maliit/keyboard#171]
When used in combination with kde plasma mobile there are some usability issues:

* sometimes the on screen keyboard doesn't show up, but still takes up space and the button to hide the on screen keyboard still exists (maybe a kde issue?)
* switching between letters and numbers/special symbols with the on screen keyboard takes upwards of a second rather than being instantaneous.
* sometimes the on screen keyboard ignores my input. i suspect this happens when i'm just off center with my tap.
* sometimes the on screen keyboard spuriously deactivates while typing (maybe a kde issue?)

**Comment by dobey** [comment]
Hi,

Generally, separate issues should be filed individually, however, I will start off saying that I have not normally seen any of these issues on phones, and the keyboard has been in use on phones for about a decade now. Are you certain there isn't some other process running on your phone consuming all the CPU and perhaps other resources? The problems you have described, generally sound like that would be the core problem you are hitting.

If you have enabled SSH on your phone, I would highly recommend connecting to the device over SSH, watching `top` and checking session logs such as with `journalctl -b --user -f` to follow the user session log where systemd is used, for example. 

Thanks.
