### ISSUE TITLE
QSoundEffect(pulseaudio): Error decoding source file:///usr/share/maliit/keyboard2/sounds/key_tick2_quiet.wav

### ISSUE THREAD

**Issue by hungrymonkey** [maliit/keyboard#173]
May I ask why both dmitry and Ionic have issues with this missing wav file?

lsb_release -a
LSB Version:    n/a
Distributor ID: openSUSE
Description:    openSUSE Tumbleweed
Release:        20220922
Codename:       n/a

Information for package maliit-keyboard:
----------------------------------------
Repository     : home:dmitry-s
Name           : maliit-keyboard
Version        : 2.3.1-9.4
Arch           : x86_64
Vendor         : obs://build.opensuse.org/home:dmitry-s
Installed Size : 6.5 MiB
Installed      : Yes
Status         : up-to-date
Source package : maliit-keyboard-2.3.1-9.4.src
Upstream URL   : https://github.com/maliit/keyboard
Summary        : Maliit virtual keyboard
Description    : 
    Maliit provides a flexible and cross-platform input method framework.
    It has a plugin-based client-server architecture where applications
    act as clients and communicate with the Maliit server via input
    context plugins. The communication link currently uses D-Bus. Maliit
    is an open source framework (LGPL 2) with open source plugins (BSD).

 5 | home_dmitry-s                     | home:dmitry-s                                       | Yes     | (r ) Yes  | Yes     | https://download.opensuse.org/repositories/home:/dmitry-s/openSUSE_Tumbleweed/

https://build.opensuse.org/package/show/home:KaratekHD:branches:home:Ionic:branches:M17N:Maliit/maliit-framework

~> maliit-keyboard 
wordengine.cpp plugin "/usr/lib64/maliit/keyboard2/languages/en/libenplugin.so" loaded
inputmethod_p.h registerActiveLanguage(): activeLanguage is: "en"
in inputMethod.cpp setActiveLanguage() activeLanguage is: "en"
DB path: /usr/lib64/maliit/keyboard2/languages/en/database_en.db
spellechecker.cpp in setLanguage() lang= "en" dictPath= "/usr/share/hunspell"
spellechecker.cpp in setLanguage() aff_file= "/usr/share/hunspell/en_US.aff" dic_file= "/usr/share/hunspell/en_US.dic" user dictionary= "/home/doof/.local/share/maliit-keyboard/en_userDictionary.dic"
inputMethod::reset()
in clear preedit.. clearing word engine
QSoundEffect(pulseaudio): Error decoding source file:///usr/share/maliit/keyboard2/sounds/key_tick2_quiet.wav
keyboard is reporting <x y w h>: < 0 488 0 312 > to the app manager.
keyboard is reporting <x y w h>: < 0 488 1280 312 > to the app manager.

https://bugzilla.opensuse.org/show_bug.cgi?id=1184014

**Comment by dobey** [comment]
This is a non-fatal error message which can be ignored. It appears, as the sound file was removed to clear up the licensing situation a little more, and has not been replaced. Audio feedback for key presses is also off by default.

**Comment by pboling** [comment]
It can be ignored, but the added noise is itself a problem.  Since it appears to have been forgotten, perhaps this should be reopened until it is fixed?
