### ISSUE TITLE
Changing keybord language does not change maalit layout

### ISSUE THREAD

**Issue by Xwang1976** [maliit/keyboard#180]
When I change in KDE the language from GB to FR, I expect that maliit layout automatically switch to the azerty layout, but it is not the case. Is there something that I should configure? Otherwise how can I set the maliit layout and language?

**Comment by dobey** [comment]
KDE only has a settings panel for Maliit language configuration, for Plasma Mobile, I think. A settings app is not yet provided by Maliit itself, and Maliit being an on-screen keyboard designed for mobile devices, does not follow configuration of hardware keyboard layout settings in any environment.

You can use `dconf-editor` GUI or `gsettings` CLI  to manually alter the settings values for Maliit though, to enable other layouts.
