### ISSUE TITLE
Adding arrow keys, ctrl, esc

### ISSUE THREAD

**Issue by plover43** [maliit/keyboard#191]
Can someone point me in the right direction for adding arrow keys, ctrl and escape to Maliit? Without those keys, it's impossible for me to replicate functionality of my keyboard using the touch screen. 

I can do a pr, just need to be pointed in the right direction for making this change. Thanks

**Comment by urbenlegend** [comment]
> In other applications, keyboard usage with modifier keys as such generally should be replaced with other more fluid interactions in the app, though.

When using maliit on a PC tablet, modifier keys are sometimes necessary. Not all apps will support touch controls. Other apps have shortcuts that are easier to use than interacting with several touch elements.

I would prefer an "advanced mode" just like the Windows 11 keyboard does that offers the full keyboard layout.

**Comment by lokman2k5** [comment]
> > In other applications, keyboard usage with modifier keys as such generally should be replaced with other more fluid interactions in the app, though.
> 
> When using maliit on a PC tablet, modifier keys are sometimes necessary. Not all apps will support touch controls and I think it is unrealistic to expect all Linux apps to care about touch. Other apps have keyboard shortcuts that are easier to use than interacting with several touch elements.
> 
> I would prefer an "advanced mode" just like the Windows 11 keyboard does that offers the full keyboard layout.

did you find a resolution to this? I am looking for a keyboard that allows ctrl super and such buttons on Wayland.
