### ISSUE TITLE
Many incorrect keycodes output

### ISSUE THREAD

**Issue by pdf** [maliit/keyboard#198]
I have a fresh install of Fedora 38 with:

maliit-keyboard v2.3.1
maliit-framework v2.3.0

All of the keys on the symbols page output completely different keycodes than the keyboard buttons render, except for the number row, `-=\/;` and `'` (though the latter kicks the keyboard out to the main letters page on press). And the shift key does not produce uppercase output - the keyboard visually changes to uppercase, but only lowercase letters are output.

Any clue how to debug or fix this?

**Comment by pdf** [comment]
- Desktop Environment: Plasma Mobile (x86_64)
- Display Server: Wayland
- Language: English
- Applications: All

**Comment by dobey** [comment]
Then something else weird is going on, as I've not seen anyone else having this issue, and it has been quite well tested on Plasma Mobile on other distros on pinephone & pro.

**Comment by pdf** [comment]
I don't doubt something weird is going on, but I'm not familiar enough with the project to know how to determine what that is.

All I did was download and install the Fedora KDE spin, then install `plasma-mobile` and `plasma-settings`, login under the Plasma Mobile session, and enable maliit as the virtual keyboard. Normal keyboard input works fine, but not maliit.

Perhaps there's some extra *something* installed by the dedicated pinephone distro(s) that allows maliit to work properly?

**Comment by pdf** [comment]
I was able to solve this by manually installing the files from https://github.com/KDE/plasma-phone-settings - I suspect in particular the following section in `/etc/xdg/kwinrc` was responsible for allowing maliit to function correctly:

```
[Wayland]
InputMethod[$e]=/usr/share/applications/com.github.maliit.keyboard.desktop
VirtualKeyboardEnabled=true
```

**Comment by Justinzobel** [comment]
I thought a lot of that was being merged into Plasma Mobile itself directly, apparently not. I guess I'll need to package up the settings. I'll chat to the PM folks about it first though.

**Comment by Sqaaakoi** [comment]
I have been experiencing this same issue, with a very similar environment (Plasma desktop, x86-64)

**Comment by Sqaaakoi** [comment]
Okay; this is only experienced with Chromium based apps, and can be solved by adding `--enable-wayland-ime` to the command line of those apps

**Comment by compilebunny** [comment]
@Justinzobel I am experiencing the same issue. Plasma mobile 6.2 does not have /etc/xdg/kwinrc, but each user has .config/kwinrc. My .config/kwinrc has the text that @pdf provided without the [$e]. 

I also tried the text that @pdf provided in its entirety -- this did not work.

Edit: in reference to @Sqaaakoi 's comment, this is experienced everywhere with plasma mobile 6.2.

Edit 2: Not clear whether the text that @pdf provided works. The system automatically modifies ~/.config/kwinrc by adding 

````
InputMethod=/usr/share/applications/com.github.maliit.keyboard.desktop
````

ahead of 

````
InputMethod[$e]=/usr/share/applications/com.github.maliit.keyboard.desktop
````
