### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by topiasv** [maliit/keyboard#2]
I am confused what kind of licensing each file has because there are 3 different licenses. In commit https://github.com/maliit/keyboard/commit/6430c82f2b1b30ea98d65b73ae2dc628ba230ef8 the debian directory was deleted and along with it the copyright file which listed all the licenses for each component. I don't know if deleting the copyright file was intentional but now it's unclear what kind of licensing model this project has.

**Comment by jpetersen** [comment]
Yes I would prefer BSD-3-clause for all old code which had it and new code, but yes some code from Canonical is a different license.

I do not mind a file describing which license is used for which files.

**Comment by KAMiKAZOW** [comment]
Well, https://github.com/maliit/keyboard/blob/master/src/plugin/device.cpp has your copyright but it's LGPL-3-only. Perhaps an oversight? You can change your own code's license as you wish. Same with the feedback and theme files.

**Comment by jpetersen** [comment]
Right good point, I will adjust it in my code.
