### ISSUE TITLE
Permit to manually open and close the keyboard avoiding the automatic logic

### ISSUE THREAD

**Issue by Xwang1976** [maliit/keyboard#202]
Sometimes the automatic logic that should open maliit when tapping on a text field fails, but if tapping on other apps it is possible to open the  keyboard, the keyboard often works also with the app with which it was not possible to open the keyboard automatically. 
It would be great f it is possible for the user to select a manual activation deactivation which opens and closes the keyboard by click on the tray icon.

**Comment by Xwang1976** [comment]
> It is already possible to open the keyboard manually. I don't know how it works on other desktop environments. but on KDE there is a tray icon for that and on Plasma Mobile you can activate the function in the Setting App (You'll find it in the shell subcategory).
> 
> ![Screenshot_20231214_133945](https://private-user-images.githubusercontent.com/94069499/290522472-ff0e3c48-ab5b-44ad-85e5-2dcebc6fbad5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI1Nzg3NjEsIm5iZiI6MTcwMjU3ODQ2MSwicGF0aCI6Ii85NDA2OTQ5OS8yOTA1MjI0NzItZmYwZTNjNDgtYWI1Yi00NGFkLTg1ZTUtMmRjZWJjNmZiYWQ1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE0VDE4Mjc0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYxZTEzMGEzNjU5MmIzNDRiOWM5NDJiNTZmMTlkNDZlZjc4ZDdkZWE0YWFlMGE4NzNmMzM2NDViMDdlYTViNGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-14oXe8b8dx3KrxJWRD_Qx76q83pbWtncOGRqi0qqZw)
> 
> ![Screenshot_20231214_135343](https://private-user-images.githubusercontent.com/94069499/290523909-a82c8e9f-41ef-43e7-88d0-b33558fcfb3c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI1Nzg3NjEsIm5iZiI6MTcwMjU3ODQ2MSwicGF0aCI6Ii85NDA2OTQ5OS8yOTA1MjM5MDktYTgyYzhlOWYtNDFlZi00M2U3LTg4ZDAtYjMzNTU4ZmNmYjNjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE0VDE4Mjc0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNkZDJmOWRkNTZmNTk2N2I4MmU5NDQ0OWZkMGY1MzBhNzE0MzRlZmZiODU0ZmE0MzM4YjMzMzBlZTY0ZWJlMmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.d8sLIXlZsKjOcPIhZmzhIE4xKd6DTr2DNtGuhS4xYYU)

I'm using KDE on my archlinux and I've the keyboard icon, but that permits only to deactivate the keabord, reactivate it and close it if it is open, but not to open it. To open the keybord I've to tap on a writable part of the desktop and if I close the keyboard when I'm using it with the Konsole, then it does not reopen again. I'v' to open another konsole instance and then tap on it to have the keyboard opening again.
On Firefox instaed it reopens but in any case I've to tap on a writable part of the page.down
So to reassume there is a downward pointing arrow when the keyboard is open, but not an upward arrow to open it.

**Comment by dobey** [comment]
> I'v' to open another konsole instance and then tap on it to have the keyboard opening again.

This sounds like a bug in Plasma then.

> On Firefox instaed it reopens but in any case I've to tap on a writable part of the page.down

Yes, tapping on a text entry field again is the correct way to request the keyboard be shown again.

> So to reassume there is a downward pointing arrow when the keyboard is open, but not an upward arrow to open it.

That applet is part of Plasma, not maliit. You should open an issue about it at bugs.kde.org if you think it should also have a feature to open the keyboard arbitrarily (though, this is likely to be problematic anyway, as I think tapping that button takes focus away from where you want to type, so the keyboard would not open because there's no focused text field).
