### ISSUE TITLE
unable to get keyboard to popup via any method (KDE Plasma Ubuntu Noble 24.04 Xorg)

### ISSUE THREAD

**Issue by theofficialgman** [maliit/keyboard#206]
ubuntu places a script in xinput.d to start maliit-server, however this does not appear to do anything as maliit-server isn't running when I check after login
```
cat /etc/X11/xinit/xinput.d/maliit
XIM=none
XIM_PROGRAM=/usr/bin/maliit-server
XIM_ARGS=

GTK_IM_MODULE=Maliit
QT_IM_MODULE=MaliitPhablet

DEPENDS="maliit-framework"
```

manually running maliit-server
```
maliit-server 
wordengine.cpp plugin "/usr/lib/aarch64-linux-gnu/maliit/keyboard2/languages/en/libenplugin.so" loaded
inputmethod_p.h registerActiveLanguage(): activeLanguage is: "en"
in inputMethod.cpp setActiveLanguage() activeLanguage is: "en"
DB path: /usr/lib/aarch64-linux-gnu/maliit/keyboard2/languages/en/database_en.db
spellechecker.cpp in setLanguage() lang= "en" dictPath= "/usr/share/hunspell"
spellechecker.cpp in setLanguage() aff_file= "/usr/share/hunspell/en_US.aff" dic_file= "/usr/share/hunspell/en_US.dic" user dictionary= "/home/gman/.local/share/maliit-server/en_userDictionary.dic"
inputMethod::reset()
in clear preedit.. clearing word engine
keyboard is reporting <x y w h>: < 0 112 160 48 > to the app manager.
QSoundEffect(pulseaudio): Error decoding source file:///usr/share/maliit/keyboard2/sounds/key_tick2_quiet.wav
keyboard is reporting <x y w h>: < 0 1032 160 48 > to the app manager.
keyboard is reporting <x y w h>: < 0 659 160 421 > to the app manager.
keyboard is reporting <x y w h>: < 0 659 1920 421 > to the app manager.
```

now how can I get the keyboard to popup? I would like to manually launch it at will via terminal for testing or some other method. Nothing I have attempted works.

**Comment by dobey** [comment]
You need to have `QT_IM_MODULE=maliit` in the environment for Qt5 apps, for them to pop the keyboard open under Xorg.

**Comment by theofficialgman** [comment]
@dobey lets re-open then. noble updated the package to include that change.
having maliit installed causes the session to hang on launch

**Comment by dobey** [comment]
> @dobey lets re-open then. noble updated the package to include that change. having maliit installed causes the session to hang on launch

Report the issue in your distribution's issue tracker then. And that is unrelated to the question asked in this ticket.
