### ISSUE TITLE
Dependency for KDE Plasma 6 running in openSUSE Tumbleweed

### ISSUE THREAD

**Issue by muhammadrefa** [maliit/keyboard#219]
I am using openSUSE Tumbleweed 20240613 running KDE Plasma 6. Virtual keyboard has been configured, but the keyboard does not show up. When running `maliit-keyboard` in Konsole, I got this message:
```qt.qpa.plugin: Could not find the Qt platform plugin "wayland" in ""```

`qt6-wayland` that provides `/usr/lib64/qt6/plugins/platforms/libqwayland*.so` has been installed.  
Problem solved by installing `libqt5-qtwayland` that provides `/usr/lib64/qt5/plugins/platforms/libqwayland*.so`

Maybe it is a good idea to add `libqt5-qtwayland` as a dependency for `maliit-keyboard`

Software/OS version:
- openSUSE Tumbleweed 20240613
- `maliit-keyboard` 2.3.1-4.12 from `M17N:Maliit` repository
- KDE Plasma 6.0.5
- KDE Frameworks 6.3.0
- Wayland

**Comment by dobey** [comment]
We don't maintain packaging in distributions. Please open an issue with your distributor, OpenSUSE, instead.
