### ISSUE TITLE
Manually open the keyboard?

### ISSUE THREAD

**Issue by Nickdnepr** [maliit/keyboard#22]
Is there any way to open the keyboard manually? It does not open when I highlight text inputs in some applications, and i can't find any way to open it manually.

**Comment by jpetersen** [comment]
I think it is mostly a question why the keyboard does not open.

I am not sure on what level the keyboard could be opened (maybe from compositor). But then the other question is does the input field even gets the text when it does not realize it needs to show a virtual keyboard.

**Comment by Nickdnepr** [comment]
It gets. When i plug in the physical keyboard and try to type text it works fine. A couple of words about my hardware and software to make things a bit more clear: I use Pinephone with Manjaro(plasma mobile) distro installed. Some applications like telegram desktop, element (riot) client, freetube launch fine and behave identically in kde, phosh and lomiri graphical environments: neither of them does not open the virtual keyboard automatically. However, phosh's and lomiri's keyboards does have the button to open the keyboard manually. Probably this could be manjaro's problem, but i can't say for sure until i have a chance to test maliit keyboard on different distro.

**Comment by plata** [comment]
> It does not open when I highlight text inputs in some applications

I have this issue mainly with Firefox.

> and i can't find any way to open it manually

You can swipe up from the bottom of the screen two times.

**Comment by Crono23** [comment]
> You can swipe up from the bottom of the screen two times.
Does this functionality exist for desktop too? I can't seem to bring it up manually.

**Comment by dobey** [comment]
> Does this functionality exist for desktop too? I can't seem to bring it up manually.

I don't know that such functionality exists anywhere. And without a touch screen, there's certainly no way to swipe up from bottom of the screen. At least, this double swipe does not exist/work in either Plasma Mobile or Ubuntu Touch for me. There also isn't really anything we can do in the keyboard itself to provide a way to manually open the keyboard, at least visually like that. It depends on the shell being used to provide some such method, as users may decide to use a different OSK solution, and we (maliit keyboard) have no concept of where or how, an appropriate method of visualization would be, as for example Plasma Mobile has a navigation bar at the bottom of the screen, Ubuntu Touch reserves bottom edge swipes for applications, traditional PC systems don't always have touch screens, etc…

I don't think there is really anything we can do in keyboard itself to resolve this issue. If the keyboard doesn't open when a text entry is selected, it's a problem of the system itself, not the keyboard, usually.

**Comment by the-cave-dweller** [comment]
> t least visually like that. It depends on the shell being used to provide some such method, as users may decide to use

Is there any way to configure this on a Pinephone?

**Comment by dobey** [comment]
> Is there any way to configure this on a Pinephone?

Plasma Mobile does not have any method to manually open the keyboard, no. And even if it did, it would still not work because the application where this is necessary is not communicating via the input method protocols, otherwise it would have opened the keyboard when focusing a text entry.

Maliit is an input method and not an emulator of hardware keyboard input, and manually opening the keyboard panel from elsewhere is outside the purview of maliit, so I am closing this as there is nothing we can do in maliit itself.
