### ISSUE TITLE
Thinkpad-like Joystick

### ISSUE THREAD

**Issue by Izaic** [maliit/keyboard#24]
Windows 10 Mobile had a joystick in the virtual keyboard for cursor navigation... Is that something that could be added to maliit?

**Comment by kugiigi** [comment]
You can press and hold the spacebar and swipe to move the cursor. Maybe joystick is faster to use but doesn't that prone for accidental movement? I personally never tried one though so I'm not sure.

**Comment by jpetersen** [comment]
Sounds like a cool feature so sure we can add it.

Maybe would be good when we have a way to make it possible to modify/customize the layouts more easily

**Comment by dobey** [comment]
Indeed, long press on _Space_ will switch to cursor mode, which now also has an additional selection mode enabled by double tapping on the blank area of cursor mode. So, I'm going to consider this closed now. Thanks.
