### ISSUE TITLE
Make a release

### ISSUE THREAD

**Issue by KAMiKAZOW** [maliit/keyboard#32]
KDE Plasma Mobile uses this keyboard but many Linux distributions don't like to ship random Git snapshots.
Considering how long this code has been in use already under various stewards, I think even releasing a "Maliit Keyboard 2.0" (as opposed to Mayliit Keyboard 2, beta 1) doesn't seem that outlandish to me.

My personal preference for a release cycle down the line would be to align it with Plasma releases because the majority of commits come from KDE developers like @bhush9 already, so maybe he could be given the permissions to press the Make Release button if @jpetersen is occupied with other stuff?

**Comment by jpetersen** [comment]
Yes I am all for being pragmatic. So if anybody wants to step up. Welcome :)

**Comment by KAMiKAZOW** [comment]
Apart from maybe my licensing PR, is there any reason not to release 2.0.0?

**Comment by jpetersen** [comment]
I do not mind to make a release.

**Comment by KAMiKAZOW** [comment]
I'll think of a few lines for an announcement and add them here as a comment. Feel free to reuse it, change it however you like, or don't do anything with it.

**Comment by KAMiKAZOW** [comment]
Instead of writing it down as a comment here, I created https://github.com/maliit/maliit.github.io/pull/2

**Comment by jpetersen** [comment]
Thanks a lot. Done.
