### ISSUE TITLE
Words on suggestion list extremely small and no way to change font size

### ISSUE THREAD

**Issue by tusooa** [maliit/keyboard#36]
Gentoo GNU/Linux, X11, compiled from source at branch master.
maliit-keyboard @ 1a8af6de
maliit-framework @ a478e92

The gsettings does not have any option to set font.
```
] gsettings list-recursively  org.maliit.keyboard.maliit
org.maliit.keyboard.maliit spell-checking true
org.maliit.keyboard.maliit spell-checking-languages @as []
org.maliit.keyboard.maliit auto-capitalization true
org.maliit.keyboard.maliit double-space-full-stop true
org.maliit.keyboard.maliit theme 'Ambiance'
org.maliit.keyboard.maliit previous-language 'emoji'
org.maliit.keyboard.maliit stay-hidden false
org.maliit.keyboard.maliit key-press-feedback-sound '/usr/share/maliit/keyboard2/styles/ubuntu/sounds/key_tick2_quiet.wav'
org.maliit.keyboard.maliit key-press-haptic-feedback true
org.maliit.keyboard.maliit predictive-text true
org.maliit.keyboard.maliit enabled-languages ['en', 'emoji', 'zh-hans']
org.maliit.keyboard.maliit disable-height false
org.maliit.keyboard.maliit auto-completion true
org.maliit.keyboard.maliit opacity 1.0
org.maliit.keyboard.maliit key-press-feedback false
org.maliit.keyboard.maliit active-language 'zh-hans'
org.maliit.keyboard.maliit plugin-paths ['/custom/share/maliit/plugins/org/maliit/lib/']
org.maliit.keyboard.maliit device 'default'
```

Screenshot:

![Screenshot_20210407_205628](https://user-images.githubusercontent.com/299873/113952515-d1e8d700-97e3-11eb-96b8-0b6e7d395f36.png)

**Comment by tusooa** [comment]
I seem to have found the place.

A viable workaround is

] cd $maliitPrefix
] cp -v share/maliit/keyboard2/devices/{default,something}.json

Edit share/maliit/keyboard2/devices/something.json , change wordRibbonHeight and wordRibbonFontSize to as large as one want.

] gsettings set org.maliit.keyboard.maliit device something

Deeper problem:

What are the units for height and font size? 
There is also a bug in share/maliit/keyboard2/devices/tablet.json , which used "wordribbonHeight" instead of the correct "wordRibbonHeight".

**Comment by jpetersen** [comment]
It should be possible to have an user specific configuration in ~/.local/share/maliit/keyboard2/devices/something.json and set the setting to "something".

The values are mostly relative to the defined defaultGridUnitPx. But not all of the values, and also not sure, if there is an easy way to define something based on screenSize or something.
