### ISSUE TITLE
Suggestion words disappear upon pressing Backspace

### ISSUE THREAD

**Issue by tusooa** [maliit/keyboard#38]
On master

1. Switch layout to zh-hans
2. Type something
3. Press Backspace
4. Press Enter

Observed:
on 3: Suggestion words disappeared.
on 4: Primary suggestion for what is typed in 2 is inputted.

Expected:
on 3: Suggestion words should be shown.
on 4: Primary suggestion for what is typed in 2, minus the last one character, should be inputted.

Video:
https://tusooa.xyz/_matrix/media/r0/download/tusooa.xyz/OIxkmLSjmlgxpMydWKpjRsdU

**Comment by dobey** [comment]
So, I am not seeing this issue in the current version of the keyboard, at least for Pinyin keyboard. However, #39 does seem to still be present, as after selecting a word candidate, and then pressing backspace, the Hanzi is not replaced with the Pinyin preedit text.

Also, I do have an issue similar to #39 but in English (and other languages using the western language features plugin code), where after selecting a word, and then hitting backspace, preedit is not reentered and word candidates do not reappear.
