### ISSUE TITLE
The radio button would be more standard for switching keyboard layouts

### ISSUE THREAD

**Issue by nesnera** [maliit/keyboard#48]
Enable multiple key layouts and hold down the language switch key - a checkbox will appear instead of a radio button.

Linux plasma-mobile 5.12.9-1-MANJARO-ARM #1 SMP Thu Jun 3 10:11:08 UTC 2021 aarch64 GNU/Linux
maliit-keyboard 2.0.0-2

**Comment by dobey** [comment]
This isn't an issue with Maliit itself, as the indicators are handled by the style used for `QtQuick.Controls 2.x`. It seems Plasma is not starting maliit-keyboard with the appropriate Plasma style. Perhaps this issue would be better reported at https://invent.kde.org/plasma/plasma-workspace instead. Thanks!

**Comment by dobey** [comment]
Sorry. It seems that the keyboard is indeed using the correct `org.kde.breeze` style, but that style however is rendering all MenuItem indicators as checks, even when they are radio items. I've opened https://invent.kde.org/plasma/qqc2-breeze-style/-/issues/19 about this issue now.
