### ISSUE TITLE
Build against QT 5.15.2 fails

### ISSUE THREAD

**Issue by oberon-manjaro** [maliit/keyboard#53]
Please see attached build log:
[maliit.log](https://github.com/maliit/keyboard/files/6738535/maliit.log)

**Comment by oberon-manjaro** [comment]
The offending commit is apparently the very latest (https://github.com/maliit/keyboard/commit/14b96f8e81d48e575aca67f48e7cfce82109412c)
https://github.com/maliit/keyboard/commit/81bfdd2435368628ad4bd12e94f3a7b6bf3515fc still builds fine for me.

**Comment by tusooa** [comment]
Not sure why I can compile it.

**Comment by tusooa** [comment]
@oberon-manjaro Does https://github.com/tusooa/keyboard/tree/tusooa/53-default-arg-conn compile for you?

**Comment by oberon-manjaro** [comment]
@tusooa , sorry I was offline for a while. Just tried your patch and keyboard now compiles again for me 👍🏻

**Comment by oberon-manjaro** [comment]
For me this doesn't resolve the issue but produces other errors. See
[build log](https://github.com/maliit/keyboard/files/7072768/maliit-keyboard_build.log)

**Comment by tusooa** [comment]
> For me this doesn't resolve the issue but produces other errors. See attached [build log](https://github.com/maliit/keyboard/files/7072768/maliit-keyboard_build.log)

Seems that maliit cannot be compiled with c++17.
https://gitlab.com/bingch/gentoo-overlay/-/blob/master/x11-misc/maliit-keyboard/maliit-keyboard-2.0.0-r1.ebuild

**Comment by oberon-manjaro** [comment]
Definitely Thank you 
https://gitlab.manjaro.org/packages/kde-unstable/mobile/maliit-keyboard/-/commit/4e8fc30f28d3347abbbc6e58df0ba23f73e05ef7#9b9baac1eb9b72790eef5540a1685306fc43fd6c_33_33
