### ISSUE TITLE
unit tests cannot be build (and run)

### ISSUE THREAD

**Issue by PureTryOut** [maliit/keyboard#7]
I'm trying to compile this for Alpine Linux/postmarketOS, but am having some issues.

I have maliit-framework installed including the `-dev` package for it which contains the header files, cmake files and pkconfig files. However, while compiling maliit-keyboard it complains that it can't find `maliit/plugins/abstractinputmethodhost.h`.

```
/home/bart/Documents/Git/alpine/aports/testing/maliit-keyboard/src/keyboard-99cd3f439b9504881027ce1b95f8eaa89881e027/tests/unittests/common/inputmethodhostprobe.h:35:10: fatal error: maliit/plugins/abstractinputmethodhost.h: No such file or directory
   35 | #include <maliit/plugins/abstractinputmethodhost.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```

Seems CMake did find the package so I'm not sure why this is happening, `/usr/include/maliit-2/maliit/plugins/abstractinputmethodhost.h` is available.

**Comment by jpetersen** [comment]
Better build without unit tests for now. They need to be some updating

**Comment by PureTryOut** [comment]
Any progress on this by any chance @jpetersen? Don't the header files just need to be installed to `/usr/include/maliit` rather than `/usr/include/maliit-2/maliit`? Or fix the import to import `maliit-2/maliit/plugins/abstractinputmethodhost.h` instead?

**Comment by sunweaver** [comment]
Same problem here. A fix would be appreciated.
