### ISSUE TITLE
Look for themes in the other XDG specific folders too

### ISSUE THREAD

**Issue by SameExpert** [maliit/keyboard#71]
Currently themes are looked only at `/usr/share/maliit/keyboard2/themes/`. It would be better to let it look at `$XDG_DATA_DIRS` (`/usr/local/share` and `/usr/share`) and `$XDG_DATA_HOME` (`~/.local/share/`) so that custom themes could be installed there.

**Comment by dobey** [comment]
Closing this, as with #108 being merged, the keyboard no longer implements its own theme system, and relies on the QtQuick Controls 2 styles instead.
