### ISSUE TITLE
build err,how to fix it up ?

### ISSUE THREAD

**Issue by denglinglong** [maliit/keyboard#73]
make[2]：Presage_TEXT2NGRAM-NOTFOUND：命令未找到
make[2]: *** [CMakeFiles/koplugin.dir/build.make:63：database_ko.db] 错误 127
make[1]: *** [CMakeFiles/Makefile2:179：CMakeFiles/koplugin.dir/all] 错误 2
make: *** [Makefile:130：all] 错误

**Comment by dobey** [comment]
Hi, what OS are you building on? You are missing `text2ngram` command from `presage`.
