### ISSUE TITLE
Compile failes without enable-hunspell: spellchecker.cpp:111:80: error: cannot convert ‘std::string’ {aka ‘std::__cxx11::basic_string<char>’} to ‘const char*’

### ISSUE THREAD

**Issue by nrndda** [maliit/keyboard#74]
`cmake -C /var/tmp/portage_zram/portage/kde-misc/maliit-keyboard-2.1.0/work/keyboard-2.1.0_build/gentoo_common_config.cmake -G Ninja -DCMAKE_INSTALL_PREFIX=/usr -DKDE_INSTALL_USE_QT_SYS_PATHS=ON -DKDE_INSTALL_DOCBUNDLEDIR=/usr/share/help -Denable-tests=OFF -Denable-presage=OFF -Denable-hunspell=no -DCMAKE_DISABLE_FIND_PACKAGE_Qt5Feedback=ON -DCMAKE_DISABLE_FIND_PACKAGE_Anthy=ON -DCMAKE_DISABLE_FIND_PACKAGE_Pinyin=ON -DCMAKE_DISABLE_FIND_PACKAGE_Chewing=ON -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_TOOLCHAIN_FILE=/var/tmp/portage_zram/portage/kde-misc/maliit-keyboard-2.1.0/work/keyboard-2.1.0_build/gentoo_toolchain.cmake  /var/tmp/portage_zram/portage/kde-misc/maliit-keyboard-2.1.0/work/keyboard-2.1.0`

```
/var/tmp/portage_zram/portage/kde-misc/maliit-keyboard-2.1.0/work/keyboard-2.1.0/plugins/westernsupport/spellchecker.cpp: In member function ‘void SpellCheckerPrivate::addUserDictionary(const QString&)’:
/var/tmp/portage_zram/portage/kde-misc/maliit-keyboard-2.1.0/work/keyboard-2.1.0/plugins/westernsupport/spellchecker.cpp:111:80: error: cannot convert ‘std::string’ {aka ‘std::__cxx11::basic_string<char>’} to ‘const char*’
  111 |                 hunspell->add(codec->fromUnicode(stream.readLine()).toStdString());
      |                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~
      |                                                                                |
      |                                                                                std::string {aka std::__cxx11::basic_string<char>}
/var/tmp/portage_zram/portage/kde-misc/maliit-keyboard-2.1.0/work/keyboard-2.1.0/plugins/westernsupport/spellchecker.cpp:47:13: note:   initializing argument 1 of ‘int Hunspell::add(const char*)’
   47 |     int add(const char *) { return 0; }
```

**Comment by nrndda** [comment]
[build.log](https://github.com/maliit/keyboard/files/7393623/build.log)

**Comment by dobey** [comment]
I am unable to replicate this problem here on my Debian Testing setup. Building with make genearator, and `-Denable-hunspell=OFF` works fine (also works fine with `=no`). There are no errors, and hunspell is not linked. Can you recreate this building from git? Thanks.

**Comment by nrndda** [comment]
As of commit 2eebfe47e9ab206f16d7f304526c7885ba3f1aa4 still reproducible: [build.log](https://github.com/maliit/keyboard/files/7918052/build.log)
As of commit 1dca7d07a39fe90f663ebff8429956ab416c375b cannot compile: [build-1.log](https://github.com/maliit/keyboard/files/7918054/build-1.log)

**Comment by nrndda** [comment]
Using Makefiles instead of ninja produces same result: [build-2.log](https://github.com/maliit/keyboard/files/7918060/build-2.log)
