### ISSUE TITLE
Can not be used normally in fedora34

### ISSUE THREAD

**Issue by LiuXingxiang-kylinsec** [maliit/keyboard#76]
I installed maliit-framework-2.0.0-4.fc34 and maliit-keyboard-2.0.0-2.fc34 in fedora34,But it can not be used normally。
when i run maliit-server,print this information in the terminal
 WARNING: PulseAudioService: pa_context_connect() failed
WARNING: PulseAudioService: pa_context_connect() failed
WARNING: file:///usr/lib64/maliit/keyboard2/qml/Keyboard.qml:257:9: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
WARNING: file:///usr/lib64/maliit/keyboard2/qml/keys/CharKey.qml:338:5: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
WARNING: file:///usr/lib64/maliit/keyboard2/qml/keys/CharKey.qml:338:5: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
WARNING: file:///usr/lib64/maliit/keyboard2/qml/keys/CharKey.qml:338:5: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
WARNING: file:///usr/lib64/maliit/keyboard2/qml/keys/CharKey.qml:338:5: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
WARNING: file:///usr/lib64/maliit/keyboard2/qml/keys/CharKey.qml:338:5: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
WARNING: file:///usr/lib64/maliit/keyboard2/qml/keys/CharKey.qml:338:5: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
WARNING: file:///usr/lib64/maliit/keyboard2/qml/keys/CharKey.qml:338:5: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
WARNING: file:///usr/lib64/maliit/keyboard2/qml/keys/CharKey.qml:338:5: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
WARNING: file:///usr/lib64/maliit/keyboard2/qml/keys/CharKey.qml:338:5: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
WARNING: file:///usr/lib64/maliit/keyboard2/qml/keys/CharKey.qml:338:5: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
WARNING: file:///usr/lib64/maliit/keyboard2/qml/keys/CharKey.qml:338:5: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
WARNING: file:///usr/lib64/maliit/keyboard2/qml/keys/CharKey.qml:338:5: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
WARNING: file:///usr/lib64/maliit/keyboard2/qml/keys/CharKey.qml:338:5: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
WARNING: file:///usr/lib64/maliit/keyboard2/qml/keys/CharKey.qml:338:5: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
WARNING: file:///usr/lib64/maliit/keyboard2/qml/keys/ActionKey.qml:59:9: QML Image: Error decoding: file:///usr/share/maliit/keyboard2/images/keyboard-caps-disabled.svg: Unsupported image format
WARNING: file:///usr/lib64/maliit/keyboard2/qml/keys/CharKey.qml:338:5: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
WARNING: file:///usr/lib64/maliit/keyboard2/qml/keys/CharKey.qml:338:5: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
WARNING: file:///usr/lib64/maliit/keyboard2/qml/keys/CharKey.qml:338:5: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
WARNING: file:///usr/lib64/maliit/keyboard2/qml/keys/CharKey.qml:338:5: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
WARNING: file:///usr/lib64/maliit/keyboard2/qml/keys/CharKey.qml:338:5: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
WARNING: file:///usr/lib64/maliit/keyboard2/qml/keys/CharKey.qml:338:5: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
WARNING: file:///usr/lib64/maliit/keyboard2/qml/keys/CharKey.qml:338:5: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
WARNING: file:///usr/lib64/maliit/keyboard2/qml/keys/CharKey.qml:338:5: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
WARNING: file:///usr/lib64/maliit/keyboard2/qml/keys/CharKey.qml:338:5: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
WARNING: file:///usr/lib64/maliit/keyboard2/qml/keys/CharKey.qml:338:5: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
WARNING: file:///usr/lib64/maliit/keyboard2/qml/keys/CharKey.qml:338:5: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
WARNING: file:///usr/lib64/maliit/keyboard2/qml/keys/CharKey.qml:338:5: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
WARNING: file:///usr/lib64/maliit/keyboard2/qml/keys/CharKey.qml:338:5: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
WARNING: file:///usr/lib64/maliit/keyboard2/qml/keys/CharKey.qml:338:5: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
WARNING: file:///usr/lib64/maliit/keyboard2/qml/keys/CharKey.qml:338:5: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
WARNING: file:///usr/lib64/maliit/keyboard2/qml/keys/CharKey.qml:338:5: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
WARNING: file:///usr/lib64/maliit/keyboard2/qml/keys/CharKey.qml:338:5: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
WARNING: file:///usr/lib64/maliit/keyboard2/qml/keys/CharKey.qml:338:5: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
WARNING: file:///usr/lib64/maliit/keyboard2/qml/keys/CharKey.qml:338:5: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
WARNING: file:///usr/lib64/maliit/keyboard2/qml/keys/CharKey.qml:338:5: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }

**Comment by dobey** [comment]
> WARNING: file:///usr/lib64/maliit/keyboard2/qml/keys/ActionKey.qml:59:9: QML Image: Error decoding:  file:///usr/share/maliit/keyboard2/images/keyboard-caps-disabled.svg: Unsupported image format

This is the only real issue in the output you've pasted. The "onFoo" deprecations are not an issue. What exactly is the problem here?

**Comment by dobey** [comment]
Please try with the latest release, and if there is still an issue with more useful data, please open a new ticket. Thanks.
