### ISSUE TITLE
Merge with ubports keyboard

### ISSUE THREAD

**Issue by mariogrip** [maliit/keyboard#8]
So after canonical dropped the phone project we both forked the ubuntu keyboard, on our side we have made some major improvements with lots of new features, also some of new languages added. See https://github.com/ubports/keyboard-component

Example of some of the things that got added to the ubports fork is a swipe up to get a "control panel" 
![image](https://user-images.githubusercontent.com/1642635/90199093-0383dc80-ddd4-11ea-8243-85df81af9a6a.png)

But the problem is we are now both in a state where we are unable to merge as both forks have made changes in different directions (example is the move to qqc2). To slowly solve this i'll start sending pr to the things that does not touch the qml parts, as these will be easier to handle. But the question remain, how can we best solve the UI part as that will be the most challenging part?

I also want to bring up the point of maybe making the keyboard component more *pluggable* so forexample the likes of ubports and kde can made there own UI tweaks to the qml part without needing to fork the whole keyboard to do so. As for qqc2 that is fine for ubports to move to, but its missing some features that is required for a more fluid UI.

**Comment by jpetersen** [comment]
Great idea, yes the main idea of the changes here were to make it more useful also outside ubports without all the dependencies.

Maybe we could solve some things via https://doc.qt.io/qt-5/qqmlfileselector.html? So have some default component and some +ubports/ (or whatever) with variant components for ubports with ubuntu-components dependencies?

**Comment by jpetersen** [comment]
That could also be done similar for plasma components

**Comment by dobey** [comment]
I can't assign this to myself it seems, but I have started the work on doing this.

**Comment by Fuseteam** [comment]
the aforemention "swipe up" was taken out, now the "control panel" is still accessible by long pressing the space key

**Comment by dobey** [comment]
> I also want to bring up the point of maybe making the keyboard component more pluggable so forexample the likes of ubports and kde can made there own UI tweaks to the qml part without needing to fork the whole keyboard to do so. As for qqc2 that is fine for ubports to move to, but its missing some features that is required for a more fluid UI.

I think the solution to this is to further improve the keyboard QML, so that if any additional UI tweaks should be doable via qqc2 styles. This way the Suru style could perhaps add back the bottom edge swipe, without needing to touch any of the QML in the keyboard itself.
