### ISSUE TITLE
Uhh…no function keys? No compose key? No Windows/Control/Alt?? No Print screen, home, end…

### ISSUE THREAD

**Issue by ctrlcctrlv** [maliit/keyboard#80]
The title bar represents my initial shock, certainty I was doing something wrong, then dumbfounded state when I realized: nope.

I understand that this keyboard was made for mobile device support, but Plasma's developers seem to have gotten confused…OSK has a dual purpose. Accessibility and mobile. 

Please help me understand how we went from this practical application:

![image](https://user-images.githubusercontent.com/838783/147811157-6c66ab71-9be0-4317-8151-8eb55f26b9fc.png)

To this shockingly incomplete keyboard, (which by the way, amusingly abuses the Tagalog language, there is nothing “maliit” (small) about this thing, much better translation would be “pinakamalaki” (too big), maybe “malaki” (big) if we're trying to be neutral).

![image](https://user-images.githubusercontent.com/838783/147811234-f29c2431-908c-42e9-b36a-0c2e1140f854.png)

I want to help, but first I have to understand how we actually got to a place where Kwin+Wayland works _so well_ yet disabled people either have to pound sand or use a keyboard that looks ridiculous on a desktop. Was a single physically disabled person asked before this was decided to be good enough for us?

[Kvkbd](https://github.com/ctrlcctrlv/kvkbd5), which I've helped maintain for years, is unfortunately broken ATM because it is quite hard to upgrade to Wayland (though I'm trying to upgrade it and have gotten quite far)

Thanks :)

**Comment by bhush9** [comment]
I'll close this issue as maliit developers have nothing to do with the decision of the Plasma developers.

You are welcome to discuss this point in appropriate channels.

**Comment by ctrlcctrlv** [comment]
Thank you @bhush9, could you or @dobey perhaps let me know where those «appropriate channels» are?

[You called my analysis](https://twitter.com/BhushanNShah/status/1477982713428647936) «misinformed» (I don't think I've denied this, writing originally «first I have to understand how we actually got [here]») and «unfair» (don't know about that).

All I want to do is fix this problem and come up with a solution for disabled desktop users who need a Wayland OSK for Plasma+KWin, that's all. Your tweet and closure seem to say that you believe that Maliit's goal is not to be an accessibility tool for desktop users, and you told me to fix Kvkbd.

[But as I wrote on Twitter](https://twitter.com/fr_brennan/status/1478050452675645451), Kvkbd is abandonware as far as KDE b.V. is concerned. So what channels are appropriate? Maliit is all we've been given that's officially supported on Plasma.

**Comment by ctrlcctrlv** [comment]
By the way, I've done significant work on my own to fix Kvkbd: https://github.com/ctrlcctrlv/kvkbd5/commit/7fee05c34f0e013566f84170c99d087c958c2548 (LOC +279/-295)

I am just trying to fix Plasma's OSK for people like me. You work at Blue Systems @bhush9, a major KDE supporter, so you have a lot of contact with Plasma/KDE devs I don't have (I'm just a libre font developer, although I've used KDE for over a decade and patched it a few times, I don't have the experience you do). So I am not trying to be snarky or "pwn" anyone, this affects me a lot, and while I'm mildly annoyed people like me weren't considered when replacing the OSK, I just want to undertand KDE b.V.'s reasoning and get it fixed, that is all.

**Comment by dobey** [comment]
> All I want to do is fix this problem and come up with a solution for disabled desktop users who need a Wayland OSK for Plasma+KWin, that's al

Well, my first advise to you would be to calm down. The overbearing rudeness you've come at Maliit with in this report is unacceptable, and only serves to paint yourself as a toxic and unreasonable person.

Now, in your twitter thread, you mention that Arch removed kvkbd. What does that have to do with Plasma, Maliit, or KDE e.V.? Why aren't you complaining to Arch to get kvkbd5 included instead? If it can be made to work under Wayland, would it not satisfy your complaints?

Ranting about things that maliit-keyboard has never supported, and acting like it is somehow responsible for the decisions of your distribution, is just rude and will get you ignored/blocked.

I for one am all about making maliit-keyboard more accessible and able to fulfill more needs, as these needs are also present on mobile devices. PCs aren't special here. But such issues need to be presented reasonably and respectfully. Not in such a rude manner as you have done here. Maliit is maintained by a very small number of people, and is not tied to Plasma. It is meant to be usable with many environments, and yes, maliit-keyboard is based from ubuntu-keyboard, which was developed for Ubuntu on phones, and unfortunately whatever accessibility features you vaguely are alluding to, were perhaps not a major focus of its development at that time.

> Thank you @bhush9, could you or @dobey perhaps let me know where those «appropriate channels» are?

As for this, it seems you already know where kvkdbd5 is hosted. For issues with Arch, I'm sure they have an issue tracker as well as forums or such, for discussing things regarding Arch.

**Comment by ctrlcctrlv** [comment]
If I've displayed any "overbearing rudeness" then such is only displayed to make you feel how I do when accessibility features I rely on are seem as unimportant in software.

My distro doesn't have anything at all to do with it. KDE dropped kvkbd as a supported OSK. For a while it was supported by community, which was simple when KDE was targeting X11, first by compiling with old KDE4 versions of KDE's libraries, then for a brief period via the AppImage, then via the Qt5 port. In that time period, KDE seemed to be flirting with the [Qt Virtual Keyboard](https://doc.qt.io/qt-5/qtvirtualkeyboard-index.html) to replace Kvkbd] (_Cf._ [this post](https://blog.martin-graesslin.com/blog/2017/03/virtual-keyboard-on-lock-screen/) by @mgraesslin), but Kvkbd was never fully replaced.

I talk about what has happened in Arch just because _this is what the community is doing to work around Plasma/KDE's **perceived** lack of care for its physically disabled users_…now kvkbd5 is broken, I want to know **what Plasma/KDE's plans are for disability OSK, not mobile OSK, which are different use cases entirely,** if indeed it has any. And if it has none, then I'm asking those interested to start thinking of plans.

Can I fix Kvkbd5 on my own? Sure, maybe, I can figure out the APIs Maliit is calling and do the same, but I don't understand why we have to always be on the outside looking in, why can't accessibility tools reclaim the prior importance **to KDE** they once had?

> Ranting about things that maliit-keyboard has never supported, and acting like it is somehow responsible for the decisions of your distribution, is just rude and will get you ignored/blocked.

I never did this. **KDE itself dropped support for Kvkbd, Arch just followed upstream's deprecation**.

**Comment by dobey** [comment]
I'm locking this. You clearly know where else you should be taking up your concerns relating to Plasma, KDE community, or kvkdbd, since you keep posting links to other things which you claim are where decisions were being made. You should express your concerns there, not here.

If you have specific actionable issues for Maliit, which are not already reported, please feel free to report them. Some of thee things you've ranted about here are in fact already open requests in Maliit (such as wanting Ctrl/Alt/Super modifiers). Or if you find an issue and want to make a PR, feel free to do so.

Support for many of these things also doesn't fall solely on Maliit. The input method and text input protocols for Wayland are limited or problematic for implementing some of these things. That's not an issue we can solve directly in Maliit either.

That said, I am now closing this thread, as you do not seem interested in reasonable conversation here. Please take your concerns about KDE, Arch, etc… to their appropriate places, and I would suggest doing so without such a toxic attitude or outlook towards others. Thanks.
