### ISSUE TITLE
maliit keyboard does not popup anymore

### ISSUE THREAD

**Issue by Xwang1976** [maliit/keyboard#87]
I've installed maliit a couple of months ago on my Lenovo miix-720 2 in 1 pc running archlinux and KDE with plasma.
It used to work correctly, but now it does not pop up any more.
It is in the tray, and when I tap on it a popup is showed which says that the keyboard is activated, but then it never appears.
Could you help me debugging why it doesn't work anymore, please?

**Comment by dobey** [comment]
Were you using it via maliit-server before? Or with maliit-keyboard running directly? Are either of those processes running? Have you checked your session logs to see if anything went wrong there? Which build of Plasma are you using? Released 5.23? Testing 5.24? Or kde-unstable git builds? What happens if you run `maliit-keyboard` in a terminal?

**Comment by Xwang1976** [comment]
Hi,
to run it I did just select it in the system settings virtual keyboard pane.
Neither maliit-server nor maliit-keyboard are running.
If I run maliit-server in a konsole I get the following output:
` maliit-server 
*** stack smashing detected ***: terminated
Annullato (core dump creato)
`

If I run maliit-keyboard I get:
`maliit-keyboard 
wordengine.cpp plugin "/usr/lib/maliit/keyboard2/languages/en/libenplugin.so" loaded
inputmethod_p.h registerActiveLanguage(): activeLanguage is: "en"
in inputMethod.cpp setActiveLanguage() activeLanguage is: "en"
spellechecker.cpp in setLanguage() lang= "en" dictPath= "/usr/share/myspell/dicts"
Did not find a dictionary for "en"  - checking for  "en"
No dictionary found for "en" turning off spellchecking
no dictionary to turn on spellchecking
inputMethod::reset()
in clear preedit.. clearing word engine
file:///usr/lib/maliit/keyboard2/qml/Keyboard.qml:256:9: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
file:///usr/lib/maliit/keyboard2/qml/keys/KeyIcon.qml:40:5: QML Image: Failed to get image from provider: image://icon/keyboard-enter
file:///usr/lib/maliit/keyboard2/qml/keys/KeyIcon.qml:30:5: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
file:///usr/lib/maliit/keyboard2/qml/keys/CharKey.qml:338:5: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
file:///usr/lib/maliit/keyboard2/qml/keys/CharKey.qml:338:5: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
file:///usr/lib/maliit/keyboard2/qml/keys/KeyIcon.qml:30:5: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
file:///usr/lib/maliit/keyboard2/qml/keys/CharKey.qml:338:5: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
file:///usr/lib/maliit/keyboard2/qml/keys/CharKey.qml:338:5: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
file:///usr/lib/maliit/keyboard2/qml/keys/KeyIcon.qml:40:5: QML Image: Failed to get image from provider: image://icon/language-chooser
file:///usr/lib/maliit/keyboard2/qml/keys/KeyIcon.qml:30:5: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
file:///usr/lib/maliit/keyboard2/qml/keys/CharKey.qml:338:5: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
file:///usr/lib/maliit/keyboard2/qml/keys/KeyIcon.qml:30:5: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
file:///usr/lib/maliit/keyboard2/qml/keys/CharKey.qml:338:5: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
file:///usr/lib/maliit/keyboard2/qml/keys/KeyIcon.qml:40:5: QML Image: Failed to get image from provider: image://icon/edit-clear
file:///usr/lib/maliit/keyboard2/qml/keys/KeyIcon.qml:30:5: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
file:///usr/lib/maliit/keyboard2/qml/keys/CharKey.qml:338:5: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
file:///usr/lib/maliit/keyboard2/qml/keys/CharKey.qml:338:5: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
file:///usr/lib/maliit/keyboard2/qml/keys/CharKey.qml:338:5: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
file:///usr/lib/maliit/keyboard2/qml/keys/CharKey.qml:338:5: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
file:///usr/lib/maliit/keyboard2/qml/keys/CharKey.qml:338:5: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
file:///usr/lib/maliit/keyboard2/qml/keys/CharKey.qml:338:5: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
file:///usr/lib/maliit/keyboard2/qml/keys/CharKey.qml:338:5: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
file:///usr/lib/maliit/keyboard2/qml/keys/CharKey.qml:338:5: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
file:///usr/lib/maliit/keyboard2/qml/keys/KeyIcon.qml:40:5: QML Image: Failed to get image from provider: image://icon/keyboard-caps-disabled
file:///usr/lib/maliit/keyboard2/qml/keys/KeyIcon.qml:30:5: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
file:///usr/lib/maliit/keyboard2/qml/keys/CharKey.qml:338:5: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
file:///usr/lib/maliit/keyboard2/qml/keys/CharKey.qml:338:5: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
file:///usr/lib/maliit/keyboard2/qml/keys/CharKey.qml:338:5: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
file:///usr/lib/maliit/keyboard2/qml/keys/CharKey.qml:338:5: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
file:///usr/lib/maliit/keyboard2/qml/keys/CharKey.qml:338:5: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
file:///usr/lib/maliit/keyboard2/qml/keys/CharKey.qml:338:5: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
file:///usr/lib/maliit/keyboard2/qml/keys/CharKey.qml:338:5: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
file:///usr/lib/maliit/keyboard2/qml/keys/CharKey.qml:338:5: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
file:///usr/lib/maliit/keyboard2/qml/keys/CharKey.qml:338:5: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
file:///usr/lib/maliit/keyboard2/qml/keys/CharKey.qml:338:5: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
file:///usr/lib/maliit/keyboard2/qml/keys/CharKey.qml:338:5: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
file:///usr/lib/maliit/keyboard2/qml/keys/CharKey.qml:338:5: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
file:///usr/lib/maliit/keyboard2/qml/keys/CharKey.qml:338:5: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
file:///usr/lib/maliit/keyboard2/qml/keys/CharKey.qml:338:5: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
file:///usr/lib/maliit/keyboard2/qml/keys/CharKey.qml:338:5: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
file:///usr/lib/maliit/keyboard2/qml/keys/CharKey.qml:338:5: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
file:///usr/lib/maliit/keyboard2/qml/keys/CharKey.qml:338:5: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
file:///usr/lib/maliit/keyboard2/qml/keys/CharKey.qml:338:5: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
file:///usr/lib/maliit/keyboard2/qml/keys/CharKey.qml:338:5: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
file:///usr/lib/maliit/keyboard2/qml/keys/CharKey.qml:338:5: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
keyboard is reporting <x y w h>: < 0 -8 0 8 > to the app manager.
QSoundEffect(pulseaudio): Error decoding source file:///usr/share/maliit/keyboard2/sounds/key_tick2_quiet.wav
`
This is the version:
`Sistema operativo: Arch Linux
Versione di KDE Plasma: 5.23.5
Versione di KDE Frameworks: 5.90.0
Versione di Qt: 5.15.2
Versione del Kernel: 5.16.2-arch1-1 (64 bit)
Piattaforma grafica: Wayland
Processori: 4 × Intel® Core™ i5-7200U CPU @ 2.50GHz
Memoria: 7,7 GiB di RAM
Processore grafico: Mesa Intel® HD Graphics 620`

**Comment by Xwang1976** [comment]
Do you need more info?

**Comment by Xwang1976** [comment]
Problem solved by itself with an upgrade of a lot of archlinux packages.
We can close.

**Comment by Xwang1976** [comment]
Now the issue is different. 
maliit does not popup for konsole, dolphin, calibre and the note plasmoid on the desktop. 
It works correctly with firefox, the package manager pamac (but not with the popup where you enter the user passsword) .
I do not know why. Can you help me please?

**Comment by dobey** [comment]
I have no idea why it would work on firefox and not other things. What toolkit is the password popup? Is this on Wayland or X11?

**Comment by Xwang1976** [comment]
The system uses Wayland and it seems that the behavior changes a lot from one day to the other apparently without reason (today it works almost perfectly, it just does not show up on the active window when I enable it from the disabled state, but if I minimize the window and click on an other app it appears and then it works correctly also on the minimized window).
So I wonder if there is any journal debugging mechanism which I could activate to try to understand these strange behaviors

**Comment by dobey** [comment]
In `kwin` from git master, there is now support for always showing the keyboard, if you set `KWIN_IM_SHOW_ALWAYS=1` in the environment, which you should be able to do by adding to your `~/.profile` or `~/.bashrc` or other appropriate place which would alter the environment under which KWin runs.

**Comment by dobey** [comment]
I'm closing this as it seems to not be related to malilit itself.
